-- FutoNav cloud setup: run once in the Supabase SQL Editor.
-- Generated by scripts/gen-cloud-sql.ts — do not edit by hand.

-- ============================================================
-- 1) Schema (from supabase/migrations/0001_init.sql)
-- ============================================================
create type poi_category as enum (
  'Department', 'Hostel', 'Admin', 'Cafeteria',
  'Gate', 'Sports', 'Medical', 'Library', 'Other'
);

create table public.pois (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  category    poi_category not null,
  latitude    double precision not null,
  longitude   double precision not null,
  description text check (char_length(description) <= 200),
  tags        text[] not null default '{}',
  image_url   text,
  updated_at  timestamptz not null default now()
);

create index pois_updated_at_idx on public.pois (updated_at);
create index pois_tags_gin on public.pois using gin (tags);

create or replace function set_updated_at() returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger pois_set_updated_at before update on public.pois
  for each row execute function set_updated_at();

-- ============================================================
-- 2) Row-level security (from supabase/migrations/0002_rls.sql)
-- ============================================================
alter table public.pois enable row level security;

create policy "pois readable by anyone"
  on public.pois for select
  using (true);

create policy "pois writable by admins"
  on public.pois for all
  using (auth.jwt() ->> 'role' = 'admin')
  with check (auth.jwt() ->> 'role' = 'admin');

-- ============================================================
-- 3) Baseline POI seed (idempotent)
-- ============================================================
insert into public.pois (id, name, category, latitude, longitude, description, tags, image_url)
values ('00000000-0000-0000-0000-000000000001', 'School of Engineering and Engineering Technology', 'Department', 5.3915, 7.0025, 'SEET administrative building', ARRAY['SEET', 'engineering']::text[], null)
on conflict (id) do nothing;

insert into public.pois (id, name, category, latitude, longitude, description, tags, image_url)
values ('00000000-0000-0000-0000-000000000002', 'School of Science and Technology', 'Department', 5.393, 7.001, 'SST main building', ARRAY['SST', 'science']::text[], null)
on conflict (id) do nothing;

insert into public.pois (id, name, category, latitude, longitude, description, tags, image_url)
values ('00000000-0000-0000-0000-000000000003', 'School of Agriculture and Agricultural Technology', 'Department', 5.3945, 7.0035, 'SAAT building', ARRAY['SAAT', 'agriculture']::text[], null)
on conflict (id) do nothing;

insert into public.pois (id, name, category, latitude, longitude, description, tags, image_url)
values ('00000000-0000-0000-0000-000000000004', 'School of Management Technology', 'Department', 5.3905, 7.0005, 'SMAT building', ARRAY['SMAT', 'management']::text[], null)
on conflict (id) do nothing;

insert into public.pois (id, name, category, latitude, longitude, description, tags, image_url)
values ('00000000-0000-0000-0000-000000000005', 'School of Health Technology', 'Department', 5.392, 7.004, 'SHT building', ARRAY['SHT', 'health']::text[], null)
on conflict (id) do nothing;

insert into public.pois (id, name, category, latitude, longitude, description, tags, image_url)
values ('00000000-0000-0000-0000-000000000006', 'School of Postgraduate Studies', 'Admin', 5.395, 7.002, 'SPGS building', ARRAY['SPGS', 'postgraduate']::text[], null)
on conflict (id) do nothing;

insert into public.pois (id, name, category, latitude, longitude, description, tags, image_url)
values ('00000000-0000-0000-0000-000000000007', 'University Library', 'Library', 5.3935, 7.0015, 'Main library', ARRAY['library', 'books']::text[], null)
on conflict (id) do nothing;

insert into public.pois (id, name, category, latitude, longitude, description, tags, image_url)
values ('00000000-0000-0000-0000-000000000008', 'Student Affairs Building', 'Admin', 5.391, 7.003, 'Dean of Students office', ARRAY['student', 'affairs']::text[], null)
on conflict (id) do nothing;

insert into public.pois (id, name, category, latitude, longitude, description, tags, image_url)
values ('00000000-0000-0000-0000-000000000009', 'Senate Building', 'Admin', 5.3925, 7.002, 'University Senate and VC office', ARRAY['school', 'administration']::text[], null)
on conflict (id) do nothing;

insert into public.pois (id, name, category, latitude, longitude, description, tags, image_url)
values ('00000000-0000-0000-0000-000000000010', 'Medical Centre', 'Medical', 5.394, 7.0045, 'Campus health services', ARRAY['hospital', 'clinic', 'health']::text[], null)
on conflict (id) do nothing;

insert into public.pois (id, name, category, latitude, longitude, description, tags, image_url)
values ('7801aa7d-f149-4523-b957-599998f36793', 'Admin Building', 'Admin', 5.3844287, 6.991472, 'FUTO administrative block', ARRAY['admin', 'administration']::text[], null)
on conflict (id) do nothing;

insert into public.pois (id, name, category, latitude, longitude, description, tags, image_url)
values ('6e39f299-3629-4587-a856-f106d5c6d5e6', 'Architecture Studio 5', 'Department', 5.3829836, 6.9904792, 'Department of Architecture design studio', ARRAY['architecture', 'studio']::text[], null)
on conflict (id) do nothing;

insert into public.pois (id, name, category, latitude, longitude, description, tags, image_url)
values ('6efb49d3-5d26-4aa6-90c3-c8fe02fe65b1', 'Department of Architecture', 'Department', 5.3842764, 6.9912064, 'School of Environmental Sciences - Architecture department', ARRAY['architecture', 'SOES']::text[], null)
on conflict (id) do nothing;

insert into public.pois (id, name, category, latitude, longitude, description, tags, image_url)
values ('94057d4d-88f8-49d4-89ac-bede274b2121', 'Biochemistry Department', 'Department', 5.3833561, 6.9922847, 'School of Biological Sciences - Biochemistry department', ARRAY['biochemistry', 'SOBS']::text[], null)
on conflict (id) do nothing;

insert into public.pois (id, name, category, latitude, longitude, description, tags, image_url)
values ('c098f471-ba1d-4416-8c22-0531b7a898ed', 'Entrepreneurial Studies Building', 'Department', 5.3838351, 6.9902065, 'Entrepreneurial studies teaching block', ARRAY['entrepreneurship']::text[], null)
on conflict (id) do nothing;

insert into public.pois (id, name, category, latitude, longitude, description, tags, image_url)
values ('c3672048-175a-4744-83e7-b09c620e0b25', 'GST Building (Block A)', 'Department', 5.3858714, 6.9917736, 'General Studies lecture block', ARRAY['GST', 'general studies']::text[], null)
on conflict (id) do nothing;

insert into public.pois (id, name, category, latitude, longitude, description, tags, image_url)
values ('7a9321ba-3c2c-48d3-9a55-cc071f4d12b7', 'GST Building (Block B)', 'Department', 5.3853742, 6.9922582, 'General Studies lecture block', ARRAY['GST', 'general studies']::text[], null)
on conflict (id) do nothing;

insert into public.pois (id, name, category, latitude, longitude, description, tags, image_url)
values ('ba5b6602-1dde-4ba3-ab15-4111c409349d', 'SAAT Building', 'Department', 5.384046, 6.9934228, 'School of Agriculture and Agricultural Technology', ARRAY['SAAT', 'agriculture']::text[], null)
on conflict (id) do nothing;

insert into public.pois (id, name, category, latitude, longitude, description, tags, image_url)
values ('43941526-467e-4862-8f1b-b42d404bde0f', 'SAAT Faculty', 'Department', 5.38362, 6.9937476, 'School of Agriculture and Agricultural Technology faculty offices', ARRAY['SAAT', 'agriculture']::text[], null)
on conflict (id) do nothing;

insert into public.pois (id, name, category, latitude, longitude, description, tags, image_url)
values ('e4b3670c-0732-470a-99de-d55f4d73a9a5', 'SOES Auditorium', 'Department', 5.3840368, 6.9907875, 'School of Environmental Sciences auditorium', ARRAY['SOES', 'auditorium']::text[], null)
on conflict (id) do nothing;

insert into public.pois (id, name, category, latitude, longitude, description, tags, image_url)
values ('941c72bb-0e24-471a-a5e4-6b2f4a528fd3', 'SOES Extension', 'Department', 5.3838155, 6.9919649, 'School of Environmental Sciences extension building', ARRAY['SOES']::text[], null)
on conflict (id) do nothing;

insert into public.pois (id, name, category, latitude, longitude, description, tags, image_url)
values ('fe46748d-d2e6-4028-b53c-6ba8d326d4ea', 'SOES Faculty', 'Department', 5.3850431, 6.993344, 'School of Environmental Sciences faculty offices', ARRAY['SOES']::text[], null)
on conflict (id) do nothing;

insert into public.pois (id, name, category, latitude, longitude, description, tags, image_url)
values ('adb4b49c-f2b2-46d6-952b-3a9f221c3463', 'SOES Faculty Building', 'Department', 5.385115, 6.9936537, 'School of Environmental Sciences main faculty building', ARRAY['SOES']::text[], null)
on conflict (id) do nothing;

insert into public.pois (id, name, category, latitude, longitude, description, tags, image_url)
values ('d4b00802-677c-47af-a08a-8ecae82b27d5', 'SOES Lecture Theatre', 'Department', 5.3853536, 6.9939668, 'School of Environmental Sciences lecture theatre', ARRAY['SOES', 'lecture theatre']::text[], null)
on conflict (id) do nothing;

insert into public.pois (id, name, category, latitude, longitude, description, tags, image_url)
values ('c96ab1eb-8bd5-46b0-85ab-d80923d7be1c', 'SOES Surveying Department', 'Department', 5.385218, 6.9930351, 'School of Environmental Sciences - Surveying department', ARRAY['SOES', 'surveying']::text[], null)
on conflict (id) do nothing;

insert into public.pois (id, name, category, latitude, longitude, description, tags, image_url)
values ('6850e139-1d1c-4040-9e7f-779230e67c7f', 'SOSC Extension', 'Department', 5.3821559, 6.9957225, 'SOSC extension building', ARRAY['SOSC']::text[], null)
on conflict (id) do nothing;

insert into public.pois (id, name, category, latitude, longitude, description, tags, image_url)
values ('ad96c8f7-67d8-4e97-ad31-bcec6978f9be', 'Architecture Studio 2', 'Department', 5.3844706, 6.9910524, 'Department of Architecture design studio', ARRAY['architecture', 'studio']::text[], null)
on conflict (id) do nothing;

insert into public.pois (id, name, category, latitude, longitude, description, tags, image_url)
values ('c7df61f5-045d-4dc7-8d97-84d44cab684b', 'Architecture Studio 4', 'Department', 5.3840162, 6.9914479, 'Department of Architecture design studio', ARRAY['architecture', 'studio']::text[], null)
on conflict (id) do nothing;
