// Generates supabase/setup-cloud.sql = schema (0001) + RLS (0002) + baseline
// seed inserts. Paste the output into the Supabase SQL Editor to set up a fresh
// cloud project in one go. Seed inserts use ON CONFLICT (id) DO NOTHING so it's
// safe to re-run.
//
//   npx tsx scripts/gen-cloud-sql.ts

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { BASELINE_POIS } from "../apps/mobile/src/data/baselinePois";

const root = resolve(__dirname, "..");
const init = readFileSync(resolve(root, "supabase/migrations/0001_init.sql"), "utf8");
const rls = readFileSync(resolve(root, "supabase/migrations/0002_rls.sql"), "utf8");

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const arr = (tags: string[]) =>
  tags.length ? `ARRAY[${tags.map(q).join(", ")}]::text[]` : `'{}'::text[]`;

const inserts = BASELINE_POIS.map((p) => {
  const desc = p.description == null ? "null" : q(p.description);
  const img = p.imageUrl == null ? "null" : q(p.imageUrl);
  return (
    `insert into public.pois (id, name, category, latitude, longitude, description, tags, image_url)\n` +
    `values (${q(p.id)}, ${q(p.name)}, ${q(p.category)}, ${p.latitude}, ${p.longitude}, ${desc}, ${arr(p.tags)}, ${img})\n` +
    `on conflict (id) do nothing;`
  );
}).join("\n\n");

const out = `-- FutoNav cloud setup: run once in the Supabase SQL Editor.
-- Generated by scripts/gen-cloud-sql.ts — do not edit by hand.

-- ============================================================
-- 1) Schema (from supabase/migrations/0001_init.sql)
-- ============================================================
${init.trim()}

-- ============================================================
-- 2) Row-level security (from supabase/migrations/0002_rls.sql)
-- ============================================================
${rls.trim()}

-- ============================================================
-- 3) Baseline POI seed (idempotent)
-- ============================================================
${inserts}
`;

const target = resolve(root, "supabase/setup-cloud.sql");
writeFileSync(target, out);
console.log(`Wrote ${target} (${BASELINE_POIS.length} seed rows).`);
